# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/url_broker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/url_broker.proto\"\x12\n\x03URL\x12\x0b\n\x03url\x18\x01 \x01(\t\"!\n\x08Response\x12\x15\n\rresponse_code\x18\x01 \x01(\x05\x32\x30\n\x10URLBrokerService\x12\x1c\n\x07PushURL\x12\x04.URL\x1a\t.Response\"\x00\x62\x06proto3')



_URL = DESCRIPTOR.message_types_by_name['URL']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
URL = _reflection.GeneratedProtocolMessageType('URL', (_message.Message,), {
  'DESCRIPTOR' : _URL,
  '__module__' : 'protos.url_broker_pb2'
  # @@protoc_insertion_point(class_scope:URL)
  })
_sym_db.RegisterMessage(URL)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'protos.url_broker_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_URLBROKERSERVICE = DESCRIPTOR.services_by_name['URLBrokerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _URL._serialized_start=27
  _URL._serialized_end=45
  _RESPONSE._serialized_start=47
  _RESPONSE._serialized_end=80
  _URLBROKERSERVICE._serialized_start=82
  _URLBROKERSERVICE._serialized_end=130
# @@protoc_insertion_point(module_scope)
