# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import url_broker_pb2 as protos_dot_url__broker__pb2


class URLBrokerServiceStub(object):
    """Broker service to handle URL open requests from clients
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushURL = channel.unary_unary(
                '/URLBrokerService/PushURL',
                request_serializer=protos_dot_url__broker__pb2.URL.SerializeToString,
                response_deserializer=protos_dot_url__broker__pb2.Response.FromString,
                )


class URLBrokerServiceServicer(object):
    """Broker service to handle URL open requests from clients
    """

    def PushURL(self, request, context):
        """Pushes an URL to the server to open it on the default browser
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_URLBrokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushURL': grpc.unary_unary_rpc_method_handler(
                    servicer.PushURL,
                    request_deserializer=protos_dot_url__broker__pb2.URL.FromString,
                    response_serializer=protos_dot_url__broker__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'URLBrokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class URLBrokerService(object):
    """Broker service to handle URL open requests from clients
    """

    @staticmethod
    def PushURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/URLBrokerService/PushURL',
            protos_dot_url__broker__pb2.URL.SerializeToString,
            protos_dot_url__broker__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
